### ISSUE TITLE
Missing web.config

### ISSUE THREAD

**Issue by nicolaayan** [episerver/SocialAlloy#55]
Hi, The src code doesn't seem to have a main web.config on the Episerver.SociallAlloy.Web project (master branch). Can someone look into this ASAP? Thanks

**Comment by nicolaayan** [comment]
Ooops brain fart! The answer is in the ReadMe :)

**Comment by harinarayanann** [comment]
Hi, Web.config is still missing and I could not find information in ReadMe.
